account_id = "39e0b7720b49a1fa6796546ba7b68d58"
name = "twitodon"
type = "webpack"
workers_dev = true
site = { bucket = "./public" }
compatibility_date = "2022-04-28"

vars = { ENVIRONMENT = "dev" }
kv_namespaces = [
    { binding = "TWITTER_TO_MASTODON_USERMAP", id = "e09c82417eac4f3082e706348f9366fa", preview_id = "33f1370672674c3e9821f80557842f95" },
    { binding = "MASTODON_APPS", id = "28a42b13583e4bd3839ae1cf40e61fc8", preview_id = "da2b65b1ee934f30af1b7555d8ded84e" },
]

[env.production]
vars = { ENVIRONMENT = "production" }
zone_id = "aaf98463fb45282d08b91c8f16461ef3"
route = "twitodon.com/*"
kv_namespaces = [
    { binding = "TWITTER_TO_MASTODON_USERMAP", id = "e09c82417eac4f3082e706348f9366fa", preview_id = "33f1370672674c3e9821f80557842f95" },
    { binding = "MASTODON_APPS", id = "28a42b13583e4bd3839ae1cf40e61fc8", preview_id = "da2b65b1ee934f30af1b7555d8ded84e" },
]

# [secrets]
# access_token
# access_token_secret
# bearer_token
# client_id
# client_secret
# consumer_key
# consumer_secret